// VIMP Snakes — the game simulation (movement, growth, collisions) on top of
// vimp-engine-core. Compiles to WASM for the host Worker and the browser, and
// to a Node build for tests and the headless runner (`npm run core:build`).
//
// Two exported classes: GameCore — the authoritative match in the host
// Worker, ClientCore — the per-player prediction in the tab. Everything the
// engine needs from them is generated by the two ABI macros below; only
// `new` and the game-specific client methods are hand-written.
//
// There is no `physics` module and no body tags: a snake is a polyline, and
// everything that can kill it is a distance test (`game.rs`). The engine's
// PhysicsWorld is still there and still stepped — it is simply empty.

use wasm_bindgen::prelude::*;

pub mod arena;
pub mod client;
pub mod config;
pub mod crystals;
pub mod game;
pub mod motion;
pub mod snake;

use client::ClientState;
use config::{RootClientConfig, RootConfig};
use game::GameState;
use vimp_engine_core::snapshot::SnapshotPacker;

/// Public ABI of the core for the JS host (Worker / Node test harness).
/// The field names `state` and `packer` are a contract: the macro looks them
/// up literally.
#[wasm_bindgen]
pub struct GameCore {
    state: GameState,
    packer: SnapshotPacker,
}

#[wasm_bindgen]
impl GameCore {
    /// Builds the core from the JSON config `{engine: {...}, game: {...}}`
    /// assembled by the engine from src/config/.
    #[wasm_bindgen(constructor)]
    pub fn new(config_json: &str) -> Result<GameCore, JsError> {
        let cfg: RootConfig =
            serde_json::from_str(config_json).map_err(|e| JsError::new(&e.to_string()))?;

        // both checks belong on the construction boundary: a duplicate block
        // id or a panel missing a field the core writes fails silently later
        cfg.engine.snapshot.validate().map_err(|e| JsError::new(&e))?;
        cfg.game.validate().map_err(|e| JsError::new(&e))?;

        let packer = SnapshotPacker::new(cfg.engine.snapshot.clone());

        Ok(GameCore {
            state: GameState::new(cfg.engine, &cfg.game),
            packer,
        })
    }
}

vimp_engine_core::export_game_core_abi!(GameCore);

impl GameCore {
    /// Access to the simulation for native tests (not exported to JS).
    pub fn state(&self) -> &GameState {
        &self.state
    }

    pub fn state_mut(&mut self) -> &mut GameState {
        &mut self.state
    }
}

/// Client half of the core: interpolation of snapshots and prediction of the
/// local snake. Lives in the main thread of the tab.
#[wasm_bindgen]
pub struct ClientCore {
    state: ClientState,
}

#[wasm_bindgen]
impl ClientCore {
    /// Builds the client core from `{engine: {...}, game: {...}}` assembled
    /// by the engine from CONFIG_DATA.
    #[wasm_bindgen(constructor)]
    pub fn new(config_json: &str) -> Result<ClientCore, JsError> {
        let cfg: RootClientConfig =
            serde_json::from_str(config_json).map_err(|e| JsError::new(&e.to_string()))?;

        cfg.engine.snapshot.validate().map_err(|e| JsError::new(&e))?;

        Ok(ClientCore {
            state: ClientState::new(cfg.engine, &cfg.game),
        })
    }

    // ***** game-specific methods: called only from ClientPlugin.hooks ***** //

    /// Model of the local snake (known at authorization). Without it the
    /// predictor has no speed and no turn rate and cannot move anything.
    pub fn set_model(&mut self, model: &str) {
        self.state.set_model(model);
    }

    /// Authoritative panel state (PANEL_DATA). Nothing in the prediction
    /// depends on it — the crystal count arrives in the player block — but the
    /// hook is called unconditionally and the plumbing is cheap to keep.
    pub fn sync_panel(&mut self, panel_json: &str) {
        self.state.sync_panel(panel_json);
    }
}

vimp_engine_core::export_client_core_abi!(ClientCore);
